### ISSUE TITLE
[Java] CodeGen Issue: Assignment conversion not possible from type "java.lang.Object" to type "org.zkoss.zhtml.Object"

### ISSUE THREAD

**Issue by cn-at-osmit** [apache/incubator-fury#1363]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

fury 0.4.1, Java 21, macOS 14.3

### Component(s)

Java

### Minimal reproduce step

Import these dependencies in pom.xml:
```xml
	<dependencies>
		<dependency>
			<groupId>org.furyio</groupId>
			<artifactId>fury-core</artifactId>
			<version>0.4.1</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zhtml</artifactId>
			<version>9.6.0.2-jakarta</version>
		</dependency>
		<!-- Requried to make slf4j and to see the stacktrace -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.30</version>
		</dependency>
	</dependencies>
```
And start codegen for any class from `org.zkoss.zhtml`:
```java
  Fury fury = Fury.builder().build();
  fury.register(org.zkoss.zhtml.Text.class, true);
```

### What did you expect to see?

A working fury instance ;)

### What did you see instead?

A stacktrace:
```
[main] INFO io.fury.Fury - Created new fury io.fury.Fury@1e965684
[main] WARN io.fury.serializer.ObjectStreamSerializer - class org.zkoss.zhtml.Text customized jdk serialization, which is inefficient. Please replace it with a io.fury.serializer.Serializer or implements java.io.Externalizable
[main] INFO io.fury.codegen.CompileUnit - Generate code for org.zkoss.zhtml.TextFuryCompatibleCodec_1_414493378_1883919084 took 75 ms.
Exception in thread "main" io.fury.codegen.CodegenException: Compile error: 
org.zkoss.zhtml.TextFuryCompatibleCodec_1_414493378_1883919084:
/* 0001 */ package org.zkoss.zhtml;
/* 0002 */ 
/* 0003 */ import java.util.List;
/* 0004 */ import java.util.Map;
/* 0005 */ import java.util.Set;
/* 0006 */ import io.fury.Fury;
/* 0007 */ import io.fury.memory.MemoryBuffer;
/* 0008 */ import io.fury.resolver.NoRefResolver;
/* 0009 */ import io.fury.resolver.ClassInfo;
/* 0010 */ import io.fury.resolver.ClassInfoHolder;
/* 0011 */ import io.fury.resolver.ClassResolver;
/* 0012 */ import io.fury.builder.Generated;
/* 0013 */ import io.fury.serializer.CodegenSerializer.LazyInitBeanSerializer;
/* 0014 */ import io.fury.serializer.Serializers.EnumSerializer;
/* 0015 */ import io.fury.serializer.Serializer;
/* 0016 */ import io.fury.serializer.StringSerializer;
/* 0017 */ import io.fury.serializer.ObjectSerializer;
/* 0018 */ import io.fury.serializer.CompatibleSerializer;
/* 0019 */ import io.fury.serializer.collection.AbstractCollectionSerializer;
/* 0020 */ import io.fury.serializer.collection.AbstractMapSerializer;
/* 0021 */ import io.fury.builder.Generated.GeneratedCompatibleSerializer;
/* 0022 */ 
/* 0023 */ public final class TextFuryCompatibleCodec_1_414493378_1883919084 extends GeneratedCompatibleSerializer {
/* 0024 */ 
/* 0025 */   private final NoRefResolver refResolver;
/* 0026 */   private final ClassResolver classResolver;
/* 0027 */   private final StringSerializer strSerializer;
/* 0028 */   private final io.fury.resolver.FieldResolver fieldResolver;
/* 0029 */   private Fury fury;
/* 0030 */ 
/* 0031 */   public TextFuryCompatibleCodec_1_414493378_1883919084(Fury fury, Class classType) {
/* 0032 */       super(fury, classType);
/* 0033 */       this.fury = fury;
/* 0034 */       fury.getClassResolver().setSerializerIfAbsent(classType, this);
/* 0035 */   
/* 0036 */       io.fury.resolver.RefResolver refResolver0 = fury.getRefResolver();
/* 0037 */       refResolver = ((NoRefResolver)refResolver0);
/* 0038 */       classResolver = fury.getClassResolver();
/* 0039 */       strSerializer = fury.getStringSerializer();
/* 0040 */       fieldResolver = classResolver.getFieldResolver(org.zkoss.zhtml.Text.class);
/* 0041 */   }
/* 0042 */ 
/* 0043 */   private void writeEmbedTypesHashFields(MemoryBuffer memoryBuffer, org.zkoss.zhtml.Text text1) {
/* 0044 */       memoryBuffer.writeLong(-8496222313227271017L);
/* 0045 */       Object object1 = io.fury.util.Platform.getObject(text1, 68L);
/* 0046 */       Integer _tabindex = (Integer)object1;
/* 0047 */       if ((_tabindex == null)) {
/* 0048 */           memoryBuffer.writeByte(((byte)-3));
/* 0049 */       } else {
/* 0050 */           memoryBuffer.writeByte(((byte)0));
/* 0051 */           memoryBuffer.writeVarInt(_tabindex);
/* 0052 */       }
/* 0053 */       memoryBuffer.writeLong(-7420538388875177801L);
/* 0054 */       Object object22 = io.fury.util.Platform.getObject(text1, 64L);
/* 0055 */       String _value = (String)object22;
/* 0056 */       if ((_value == null)) {
/* 0057 */           memoryBuffer.writeByte(((byte)-3));
/* 0058 */       } else {
/* 0059 */           memoryBuffer.writeByte(((byte)0));
/* 0060 */           strSerializer.writeCharsStringCompressed(memoryBuffer, _value);
/* 0061 */       }
/* 0062 */       memoryBuffer.writeLong(3973317070855116847L);
/* 0063 */       boolean value3 = io.fury.util.Platform.getBoolean(text1, 60L);
/* 0064 */       memoryBuffer.writeBoolean(value3);
/* 0065 */   }
/* 0066 */ 
/* 0067 */   private long readEmbedTypesHashFields(long value0, MemoryBuffer memoryBuffer1, org.zkoss.zhtml.Text text2) {
/* 0068 */       StringSerializer strSerializer = this.strSerializer;
/* 0069 */       io.fury.resolver.FieldResolver fieldResolver = this.fieldResolver;
/* 0070 */       if ((value0 == -8496222313227271017L)) {
/* 0071 */           if ((memoryBuffer1.readByte() != ((byte)-3))) {
/* 0072 */               int value1 = memoryBuffer1.readVarInt();
/* 0073 */               io.fury.util.Platform.putObject(text2, 68L, ((Integer)value1));
/* 0074 */           } else {
/* 0075 */               io.fury.util.Platform.putObject(text2, 68L, null);
/* 0076 */           }
/* 0077 */           value0 = memoryBuffer1.readLong();
/* 0078 */       } else {
/* 0079 */           while ((((value0 & 7L) == ((byte)7)) && (value0 < -8496222313227271017L))) {
/* 0080 */             if ((fieldResolver.skipDataBy8(memoryBuffer1, value0) == 9223372036854775806L)) {
/* 0081 */                 return 9223372036854775806L;
/* 0082 */             }
/* 0083 */             value0 = memoryBuffer1.readLong();
/* 0084 */           }
/* 0085 */           if ((value0 == -8496222313227271017L)) {
/* 0086 */               if ((memoryBuffer1.readByte() != ((byte)-3))) {
/* 0087 */                   int value5 = memoryBuffer1.readVarInt();
/* 0088 */                   io.fury.util.Platform.putObject(text2, 68L, ((Integer)value5));
/* 0089 */               } else {
/* 0090 */                   io.fury.util.Platform.putObject(text2, 68L, null);
/* 0091 */               }
/* 0092 */               value0 = memoryBuffer1.readLong();
/* 0093 */           }
/* 0094 */       }
/* 0095 */       if ((value0 == -7420538388875177801L)) {
/* 0096 */           if ((memoryBuffer1.readByte() != ((byte)-3))) {
/* 0097 */               String string = strSerializer.readCompressedCharsString(memoryBuffer1);
/* 0098 */               io.fury.util.Platform.putObject(text2, 64L, string);
/* 0099 */           } else {
/* 0100 */               io.fury.util.Platform.putObject(text2, 64L, null);
/* 0101 */           }
/* 0102 */           value0 = memoryBuffer1.readLong();
/* 0103 */       } else {
/* 0104 */           while ((((value0 & 7L) == ((byte)7)) && (value0 < -7420538388875177801L))) {
/* 0105 */             if ((fieldResolver.skipDataBy8(memoryBuffer1, value0) == 9223372036854775806L)) {
/* 0106 */                 return 9223372036854775806L;
/* 0107 */             }
/* 0108 */             value0 = memoryBuffer1.readLong();
/* 0109 */           }
/* 0110 */           if ((value0 == -7420538388875177801L)) {
/* 0111 */               if ((memoryBuffer1.readByte() != ((byte)-3))) {
/* 0112 */                   String string1 = strSerializer.readCompressedCharsString(memoryBuffer1);
/* 0113 */                   io.fury.util.Platform.putObject(text2, 64L, string1);
/* 0114 */               } else {
/* 0115 */                   io.fury.util.Platform.putObject(text2, 64L, null);
/* 0116 */               }
/* 0117 */               value0 = memoryBuffer1.readLong();
/* 0118 */           }
/* 0119 */       }
/* 0120 */       if ((value0 == 3973317070855116847L)) {
/* 0121 */           boolean value12 = memoryBuffer1.readBoolean();
/* 0122 */           io.fury.util.Platform.putBoolean(text2, 60L, value12);
/* 0123 */           value0 = memoryBuffer1.readLong();
/* 0124 */       } else {
/* 0125 */           while ((((value0 & 7L) == ((byte)7)) && (value0 < 3973317070855116847L))) {
/* 0126 */             if ((fieldResolver.skipDataBy8(memoryBuffer1, value0) == 9223372036854775806L)) {
/* 0127 */                 return 9223372036854775806L;
/* 0128 */             }
/* 0129 */             value0 = memoryBuffer1.readLong();
/* 0130 */           }
/* 0131 */           if ((value0 == 3973317070855116847L)) {
/* 0132 */               boolean value14 = memoryBuffer1.readBoolean();
/* 0133 */               io.fury.util.Platform.putBoolean(text2, 60L, value14);
/* 0134 */               value0 = memoryBuffer1.readLong();
/* 0135 */           }
/* 0136 */       }
/* 0137 */       return value0;
/* 0138 */   }
/* 0139 */ 
/* 0140 */   public org.zkoss.zhtml.Text readAndSetFields(MemoryBuffer memoryBuffer2, Object object0) {
/* 0141 */       io.fury.resolver.FieldResolver fieldResolver = this.fieldResolver;
/* 0142 */       long partFieldInfo = memoryBuffer2.readInt();
/* 0143 */       org.zkoss.zhtml.Text bean = (org.zkoss.zhtml.Text)object0;
/* 0144 */       while (((partFieldInfo & 3L) == ((byte)1))) {
/* 0145 */         if ((fieldResolver.skipDataBy4(memoryBuffer2, ((int)partFieldInfo)) == 9223372036854775806L)) {
/* 0146 */             return bean;
/* 0147 */         }
/* 0148 */         partFieldInfo = memoryBuffer2.readInt();
/* 0149 */       }
/* 0150 */       long value16 = memoryBuffer2.readInt();
/* 0151 */       partFieldInfo = ((value16 << 32) | (partFieldInfo & 4294967295L));
/* 0152 */       while (((partFieldInfo & 7L) == ((byte)3))) {
/* 0153 */         if ((fieldResolver.skipDataBy8(memoryBuffer2, partFieldInfo) == 9223372036854775806L)) {
/* 0154 */             return bean;
/* 0155 */         }
/* 0156 */         partFieldInfo = memoryBuffer2.readLong();
/* 0157 */       }
/* 0158 */       while ((((partFieldInfo & 7L) == ((byte)7)) && (partFieldInfo < -8496222313227271017L))) {
/* 0159 */         if ((fieldResolver.skipDataBy8(memoryBuffer2, partFieldInfo) == 9223372036854775806L)) {
/* 0160 */             return bean;
/* 0161 */         }
/* 0162 */         partFieldInfo = memoryBuffer2.readLong();
/* 0163 */       }
/* 0164 */       partFieldInfo = this.readEmbedTypesHashFields(partFieldInfo, memoryBuffer2, bean);
/* 0165 */       if ((partFieldInfo == 9223372036854775806L)) {
/* 0166 */           return bean;
/* 0167 */       }
/* 0168 */       while (((partFieldInfo & 7L) == ((byte)7))) {
/* 0169 */         if ((fieldResolver.skipDataBy8(memoryBuffer2, partFieldInfo) == 9223372036854775806L)) {
/* 0170 */             return bean;
/* 0171 */         }
/* 0172 */         partFieldInfo = memoryBuffer2.readLong();
/* 0173 */       }
/* 0174 */       fieldResolver.skipEndFields(memoryBuffer2, partFieldInfo);
/* 0175 */       return bean;
/* 0176 */   }
/* 0177 */ 
/* 0178 */   @Override public final void write(MemoryBuffer buffer, Object obj) {
/* 0179 */       org.zkoss.zhtml.Text text3 = (org.zkoss.zhtml.Text)obj;
/* 0180 */       this.writeEmbedTypesHashFields(buffer, text3);
/* 0181 */       buffer.writeLong(9223372036854775806L);
/* 0182 */   }
/* 0183 */ 
/* 0184 */   @Override public final Object read(MemoryBuffer buffer) {
/* 0185 */       org.zkoss.zhtml.Text text4 = new org.zkoss.zhtml.Text();
/* 0186 */       refResolver.reference(text4);
/* 0187 */       Object bean0 = (Object)text4;
/* 0188 */       org.zkoss.zhtml.Text text5 = this.readAndSetFields(buffer, bean0);
/* 0189 */       return text4;
/* 0190 */   }
/* 0191 */ 
/* 0192 */ }
	at io.fury.codegen.JaninoUtils.toBytecode(JaninoUtils.java:126)
	at io.fury.codegen.JaninoUtils.toBytecode(JaninoUtils.java:64)
	at io.fury.codegen.CodeGenerator.compile(CodeGenerator.java:144)
	at io.fury.builder.CodecUtils.loadOrGenCodecClass(CodecUtils.java:91)
	at io.fury.builder.CodecUtils.loadOrGenCompatibleCodecClass(CodecUtils.java:64)
	at io.fury.serializer.ObjectStreamSerializer$SlotsInfo.lambda$new$1(ObjectStreamSerializer.java:348)
	at io.fury.builder.JITContext.registerSerializerJITCallback(JITContext.java:132)
	at io.fury.serializer.ObjectStreamSerializer$SlotsInfo.<init>(ObjectStreamSerializer.java:345)
	at io.fury.serializer.ObjectStreamSerializer.<init>(ObjectStreamSerializer.java:118)
	at io.fury.serializer.Serializers.createSerializer(Serializers.java:131)
	at io.fury.serializer.Serializers.newSerializer(Serializers.java:106)
	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1185)
	at io.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1116)
	at io.fury.resolver.ClassResolver.getSerializer(ClassResolver.java:761)
	at io.fury.resolver.ClassResolver.register(ClassResolver.java:411)
	at io.fury.Fury.register(Fury.java:153)
	at io.fury.tests.JavaLangIssueDemo.main(JavaLangIssueDemo.java:9)
Caused by: io.fury.shaded.org.codehaus.commons.compiler.CompileException: File 'org/zkoss/zhtml/TextFuryCompatibleCodec_1_414493378_1883919084.java', Line 45, Column 46: Assignment conversion not possible from type "java.lang.Object" to type "org.zkoss.zhtml.Object"
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compileError(UnitCompiler.java:13080)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.assignmentConversion(UnitCompiler.java:11297)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.access$3900(UnitCompiler.java:237)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$7.visitRvalue(UnitCompiler.java:2765)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$7.visitRvalue(UnitCompiler.java:2755)
	at io.fury.shaded.org.codehaus.janino.Java$Rvalue.accept(Java.java:4498)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:2755)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:2742)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.access$2700(UnitCompiler.java:237)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$6.visitLocalVariableDeclarationStatement(UnitCompiler.java:1590)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$6.visitLocalVariableDeclarationStatement(UnitCompiler.java:1576)
	at io.fury.shaded.org.codehaus.janino.Java$LocalVariableDeclarationStatement.accept(Java.java:3842)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:1576)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compileStatements(UnitCompiler.java:1662)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:3665)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:3330)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1448)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compileDeclaredMethods(UnitCompiler.java:1421)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:830)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:443)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:237)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:423)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$3.visitPackageMemberClassDeclaration(UnitCompiler.java:419)
	at io.fury.shaded.org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1688)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:419)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:393)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.access$000(UnitCompiler.java:237)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:364)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler$2.visitCompilationUnit(UnitCompiler.java:362)
	at io.fury.shaded.org.codehaus.janino.Java$CompilationUnit.accept(Java.java:371)
	at io.fury.shaded.org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:362)
	at io.fury.shaded.org.codehaus.janino.Compiler.compile2(Compiler.java:271)
	at io.fury.shaded.org.codehaus.janino.Compiler.compile(Compiler.java:213)
	at io.fury.codegen.JaninoUtils.toBytecode(JaninoUtils.java:106)
	... 16 more
```

### Anything Else?

ZK is a Java framework for building enterprise web and mobile apps.
They have a Java class matching each html component, so they also have an `object` class https://github.com/zkoss/zk/blob/master/zhtml/src/main/java/org/zkoss/zhtml/Object.java that matches the `object` html tag.

This Object class in `org.zkoss.zhtml` is preferred by the compiler over `java.lang.Object` as it is in the local package.

Thinks work when I keep the `java.lang.` package prefix here: https://github.com/apache/incubator-fury/blob/main/java/fury-core/src/main/java/org/apache/fury/codegen/CodegenContext.java#L286

What is the best approach to solve this?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @cn-at-osmit , thanks for reporting this bug. We omitted `java.lang.Object` to `Object` to reduce generated code size for faster parsing and compilation. I didn't consider that the classes in  some package has higher priority than  over `java.lang`. 

Keeping `java.lang` will resolve the issue, but bloat generated code size. How about we check common classes conflict in `CodegenContext`: `Object/Integer/Long/Double/Boolean/Byte/String/Map/Set/List/Collection`, and reserve `java.lang` prefix for other classes?

**Comment by cn-at-osmit** [comment]
The conflict check sounds like a good compromise. Although I have also considered whether the check whether a class exists or not could be more expensive than setting the 'java.lang' consistently.
Therefore the cache is important ;)

I'm new to Fury and just about to implement my first use-case, so I'm not very familiar with the internals yet. Hence the questions:

    Regarding the conflict check: Is there a good helper class I can use or should I do it via Class.forName()?
    Regarding the cache: CodegenContext does not seem to have a global context. Should I only cache within the current CodegenContext instance or create a static field there to cache over multiple instances?

**Comment by chaokunyang** [comment]
1. We have a classloader query logic in `org.apache.fury.builder.CodecUtils#loadOrGenCodecClass`:
```java
    ClassLoader beanClassClassLoader =
        beanClass.getClassLoader() == null
            ? Thread.currentThread().getContextClassLoader()
            : beanClass.getClassLoader();
    try {
      // generated code imported fury classes.
      beanClassClassLoader.loadClass(Fury.class.getName());
      codeGenerator = CodeGenerator.getSharedCodeGenerator(beanClassClassLoader);
    } catch (ClassNotFoundException e) {
      codeGenerator =
          CodeGenerator.getSharedCodeGenerator(
              beanClassClassLoader, fury.getClass().getClassLoader());
    }
```

Maybe we should move it to `CodeGenerator`, then use this classloader for `java.lang.ClassLoader#loadClass(java.lang.String)` check.

2. We can create a static `ConcurrentMap` to cache class loading/check result
