### ISSUE TITLE
In asyncCompilation to true, under the condition of it. The "it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap" serialization failure

### ISSUE THREAD

**Issue by foxmia** [apache/incubator-fury#1615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

0.5.0、0.4.1

### Component(s)

Java

### Minimal reproduce step

Serialization fails only if `asyncCompilation` is `true`, there is no problem if `asyncCompilation` is `false`

```java
@Data
public class Object2ObjectOpenHashMapTest {
    Map<String, String> ext = new Object2ObjectOpenHashMap<>();
}
```
```java
ThreadSafeFury fury = Fury.builder()
        .requireClassRegistration(false)
        .withCompatibleMode(CompatibleMode.COMPATIBLE)
        .withAsyncCompilation(true)
        .buildThreadSafeFury();

Object2ObjectOpenHashMapTest object2ObjectOpenHashMapTest = new Object2ObjectOpenHashMapTest();
byte[] bytes = fury.serializeJavaObject(object2ObjectOpenHashMapTest);
```
The error message is as follows

```
Exception in thread "main" java.lang.ClassCastException: class org.apache.fury.serializer.collection.MapSerializers$JDKCompatibleMapSerializer cannot be cast to class org.apache.fury.serializer.collection.MapSerializer (org.apache.fury.serializer.collection.MapSerializers$JDKCompatibleMapSerializer and org.apache.fury.serializer.collection.MapSerializer are in unnamed module of loader 'app')
	at org.apache.fury.serializer.CompatibleSerializer.writeMapKVFinal(CompatibleSerializer.java:258)
	at org.apache.fury.serializer.CompatibleSerializer.writeSeparateFieldValue(CompatibleSerializer.java:226)
	at org.apache.fury.serializer.CompatibleSerializer.readAndWriteFieldValue(CompatibleSerializer.java:155)
	at org.apache.fury.serializer.CompatibleSerializer.write(CompatibleSerializer.java:110)
	at org.apache.fury.Fury.writeData(Fury.java:550)
	at org.apache.fury.Fury.serializeJavaObject(Fury.java:1050)
	at org.apache.fury.Fury.serializeJavaObject(Fury.java:1025)
	at org.apache.fury.ThreadLocalFury.serializeJavaObject(ThreadLocalFury.java:180)
```

### What did you expect to see?

expect it to work.

### What did you see instead?

class org.apache.fury.serializer.collection.MapSerializers$JDKCompatibleMapSerializer cannot be cast to class org.apache.fury.serializer.collection.MapSerializer (org.apache.fury.serializer.collection.MapSerializers$JDKCompatibleMapSerializer and org.apache.fury.serializer.collection.MapSerializer are in unnamed module of loader 'app')

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @foxmia  could you provide code for Object2ObjectOpenHashMap?

**Comment by foxmia** [comment]
> Hi @foxmia could you provide code for Object2ObjectOpenHashMap?

This is dependency
```xml
<dependency>
    <groupId>it.unimi.dsi</groupId>
    <artifactId>fastutil</artifactId>
    <version>8.5.6</version>
</dependency>
```
