### ISSUE TITLE
JSONObject Enum key searializer fail java.lang.ClassCastException:

### ISSUE THREAD

**Issue by 157152688** [apache/incubator-fury#1629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

0.6.0

### Component(s)

Java

### Minimal reproduce step

public enum BlackoutTakerSourceEnum {
  USER,
  RISK_CONTROL,
  MERCHANT,
  SUSPECTED_ZOMBIE_BLACKOUT;

  private BlackoutTakerSourceEnum() {
  }
}

 public void test() {
   ThreadSafeFury fury = Fury.builder()
       .withRefTracking(true).requireClassRegistration(false).withDeserializeUnexistedClass(true).withCompatibleMode(CompatibleMode.COMPATIBLE).buildThreadSafeFury();
    Map<BlackoutTakerSourceEnum, List<Long>> data = JSONObject.parseObject("{\"RISK_CONTROL\":[]}", new TypeReference<Map<BlackoutTakerSourceEnum, List<Long>>>() {                         });
    fury.deserialize(fury.serialize(data));

  }

### What did you expect to see?

searializer succec

### What did you see instead?

java.lang.ClassCastException: org.apache.fury.serializer.BlackoutTakerSourceEnum cannot be cast to java.lang.String

	at org.apache.fury.serializer.collection.MapSerializers$StringKeyMapSerializer.write(MapSerializers.java:329)
	at org.apache.fury.serializer.collection.MapSerializers$StringKeyMapSerializer.write(MapSerializers.java:318)
	at org.apache.fury.Fury.writeData(Fury.java:552)
	at org.apache.fury.Fury.write(Fury.java:316)
	at org.apache.fury.Fury.serialize(Fury.java:250)
	at org.apache.fury.Fury.serialize(Fury.java:222)
	at org.apache.fury.ThreadLocalFury.serialize(ThreadLocalFury.java:91)
	at org.apache.fury.serializer.ObjectSerializerTest.testSerializationCollectionsEmptyMap2(ObjectSerializerTest.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Which json library are you using? I can't reproduce your error

**Comment by 157152688** [comment]
Using fastJSON version 2.0.36 will result in jsonpass type exceptions. Theoretically, it should be converted to a normal map type, but in reality, it should be converted to a jsonobject type
