### ISSUE TITLE
NullPointerException when serializing a custom type

### ISSUE THREAD

**Issue by asalabaev-nymbus** [apache/incubator-fury#1633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

Fury 0.5.0, Java 17

### Component(s)

Java

### Minimal reproduce step

I have a custom complex (but not too complex) class and I Use the example from the Fury Guide to serialise it to byte[] 
I cannot provide it here due to IP but I expect this is some basic error that might be investigated from the code base.

### What did you expect to see?

A byte array

### What did you see instead?

java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.apache.fury.reflect.TypeRef$WildcardCapturer.captureAsTypeVariable(TypeRef.java:887)
	at org.apache.fury.reflect.TypeRef$WildcardCapturer$1.captureAsTypeVariable(TypeRef.java:921)
	at org.apache.fury.reflect.TypeRef$WildcardCapturer.capture0(TypeRef.java:878)
	at org.apache.fury.reflect.TypeRef$WildcardCapturer.capture0(TypeRef.java:868)
	at org.apache.fury.reflect.TypeRef$WildcardCapturer.capture0(TypeRef.java:868)
	at org.apache.fury.reflect.TypeRef$WildcardCapturer.capture(TypeRef.java:848)
	at org.apache.fury.reflect.TypeRef.resolveType(TypeRef.java:219)
	at org.apache.fury.type.TypeUtils.getMapKeyValueType(TypeUtils.java:474)
	at org.apache.fury.resolver.FieldResolver$FieldInfo.of(FieldResolver.java:754)
	at org.apache.fury.resolver.FieldResolver.<init>(FieldResolver.java:319)
	at org.apache.fury.resolver.FieldResolver.of(FieldResolver.java:206)
	at org.apache.fury.resolver.FieldResolver.of(FieldResolver.java:190)
	at org.apache.fury.resolver.ClassResolver.getFieldResolver(ClassResolver.java:1019)
	at com.mediaspectrum.sapi.wso.DatabeanFuryRefCompatibleCodec_1_128893786_1204030294.<init>(DatabeanFuryRefCompatibleCodec_1_128893786_1204030294.java:52)
	at org.apache.fury.serializer.Serializers.createSerializer(Serializers.java:129)
	at org.apache.fury.serializer.Serializers.newSerializer(Serializers.java:104)
	at org.apache.fury.serializer.ObjectStreamSerializer$SlotsInfo.<init>(ObjectStreamSerializer.java:361)
	at org.apache.fury.serializer.ObjectStreamSerializer.<init>(ObjectStreamSerializer.java:119)
	at org.apache.fury.serializer.Serializers.createSerializer(Serializers.java:129)
	at org.apache.fury.serializer.Serializers.newSerializer(Serializers.java:104)
	at org.apache.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1169)
	at org.apache.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1107)
	at org.apache.fury.Fury.write(Fury.java:312)
	at org.apache.fury.Fury.serialize(Fury.java:248)
	at org.apache.fury.Fury.serialize(Fury.java:220)
	at org.apache.fury.ThreadLocalFury.serialize(ThreadLocalFury.java:91)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by MrChang0** [comment]
maybe you can take your fury code and try run as `.withCodegen(false)`, so that we can see error more clearly. :)

**Comment by asalabaev-nymbus** [comment]
Wow, that did the trick. No clear error, it just worked! 
Do you know how impactful it would be to run with the codeGen = false as opposed to true?

**Comment by MrChang0** [comment]
> Wow, that did the trick. No clear error, it just worked! Do you know how impactful it would be to run with the codeGen = false as opposed to true?

codeGen = true will take much high performance, I missed my data sorry. however we should check why your fury run error. I guess your class maybe have a map which is not normal java class. maybe you can try a little class to test.

**Comment by asalabaev-nymbus** [comment]
I will. Thank you! This class contains inner classes and TreeMaps and ReentrantLocks, I'll try to reproduce on something simple.
BTW does Fury omit transient variables during serialisation?

**Comment by MrChang0** [comment]
`org.apache.fury.annotation.Ignore`

**Comment by asalabaev-nymbus** [comment]
But if I am using 3rd party code I cannot insert this annotation. Will the transient variables be serialised?

**Comment by MrChang0** [comment]
it will ignore transient field.

**Comment by chaokunyang** [comment]
@Munoon Seems this is a bug introduced in #1553 

> ok, I was able to reproduce a somewhat similar. And it is also similar to the #1325
> 
> now the error is the combination of the two bugs - I see both errors now. The details are below. But it maybe another issue since initially when opening this ticket there was only NullPointerException that I have seen.
> 
> ```
> Create sequential serializer failed, 
> class: class i.MyClass
> java.lang.RuntimeException: Create sequential serializer failed, 
> class: class i.MyClass
> 	at org.apache.fury.serializer.CodegenSerializer.loadCodegenSerializer(CodegenSerializer.java:52)
> 	at org.apache.fury.resolver.ClassResolver.lambda$getObjectSerializerClass$2(ClassResolver.java:954)
> 	at org.apache.fury.builder.JITContext.registerSerializerJITCallback(JITContext.java:131)
> 	at org.apache.fury.resolver.ClassResolver.getObjectSerializerClass(ClassResolver.java:952)
> 	at org.apache.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:885)
> 	at org.apache.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:782)
> 	at org.apache.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1168)
> 	at org.apache.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1107)
> 	at org.apache.fury.Fury.write(Fury.java:312)
> 	at org.apache.fury.Fury.serialize(Fury.java:248)
> 	at org.apache.fury.Fury.serialize(Fury.java:202)
> 	at i.FuryTest.testFury(FuryTest.java:43)

**Comment by Munoon** [comment]
> @Munoon Seems this is a bug introduced in https://github.com/apache/incubator-fury/pull/1553

Agree. I'm feel sick a bit right now, so I will take a look a bit later. Hopefully during this week.

**Comment by chaokunyang** [comment]
> > @Munoon Seems this is a bug introduced in #1553
> 
> Agree. I'm feel sick a bit right now, so I will take a look a bit later. Hopefully during this week.

@Munoon, health comes first! Please take all the time you need to feel better. I'll try to fix it later.
